FROM ubuntu:20.04

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  libboost-all-dev \
  libssl-dev \
  libportaudio2 \
  libportaudiocpp0 \
  portaudio19-dev \
  pkg-config \
  git

WORKDIR /app

COPY CMakeLists.txt server.cpp ./

RUN mkdir build && cd build && \
  cmake .. && \
  make

EXPOSE 8080/tcp


CMD ["./build/server"]

